### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ajbraus** [jasmines-co/toshi-text#5]
Hey team! 

Sorry I didn't give you feedback last week. Here's my observations & suggestions:

1. A very ambitious project and a big team! That raises the stakes for what you accomplish, so take your work seriously and commit to it. 
1. Good work flexing to use your team's resources more efficiently and let the texting API be handled in node.js. 
1. In the node project, careful with naming. ETH is not a clear name of what that attribute actually is, and the capitalization will be disorienting. `user.ETH` is strange. If it is a number maybe `user.ethAccount` would be clearer. Also I recommend not naming an attribute `date` and instead use `At` or `On` as in `createdAt` or `publishedOn` to be clearer. 
1. I don't see the twillio integration into the wesbite yet. That probably should be a core feature after signing up. 
1. Remember to use strong documentations and specifications for your wallet and phone API to align these together to avoid conflicts.

Overall I feel that your progress is very solid, I just would like to see more by now and definitely a lot more before spring break. To get there, you just need more hours together coding and problem solving. I recommend using time after school and on the weekends for warrooms to get those hours set aside and use them productively. 

Excited to see this end up.

**Comment by jasminedevv** [comment]
Got it. We have set blocks of time to all work together this week and are on track to hit this week's sprint goals.
